### PR TITLE
Update travis file to include io.js and latest node

### PR DESCRIPTION
**Pull request by sh1mmer**
cc @Raynos

### CODE REVIEW

**Comment by Raynos** [comment]
latest sounds like a bad idea.

If we want to support 0.12 and 1.2 then we should put 0.12 & 1.2

I don't really care too much tbh.

**Comment by sh1mmer** [comment]
I figured testing forward seems reasonable. afaik "latest" and "io.js" are the latest stable which is 0.12 and 1.2

**Comment by sh1mmer** [comment]
From http://docs.travis-ci.com/user/languages/javascript-with-nodejs/ 

> Specifying `node` or `stable` will run using the latest stable Node.js release and specifying `iojs` 
> will run using the latest stable io.js release.

**Comment by Raynos** [comment]
@sh1mmer 

It's probably not a good idea to have "latest" just like its not a good idea to `*`. It means your project can break even though it has not changed in the last few weeks just because the environment changes.

I also feel weird about saying I support 0.12 or iojs in travis when I dont run them in production or even test 0.12 or iojs locally.

**Comment by sh1mmer** [comment]
I think that's a reasonable observation. I think I'm going to find another way to keep track of future facing testing. E.g. I think it would good to have an informational status against newer (or maybe older) versions of node but I don't think it should be a blocker for anything except we are actively maintaining.

**Pull request closed without merging**
